// Builds supabase/seed.sql (fresh installs) and supabase/arabic.sql (adds Arabic to an existing store)
// from tools/demo_catalog.js + tools/arabic_content.js.
// Usage: node tools/build_seed.js
const fs = require('fs'), vm = require('vm'), path = require('path');
const root = path.join(__dirname, '..');
const ctx = { window: {} }; vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname, 'demo_catalog.js'), 'utf8'), ctx);
const { STORE, CATEGORIES, PRODUCTS, SEED_REVIEWS } = ctx.window;
const AR = require('./arabic_content.js');

const q = v => v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const j = v => `${q(JSON.stringify(v))}::jsonb`;
const arr = a => `array[${a.map(q).join(',')}]::text[]`;

const settings = {
  currency: STORE.currency, promo: { enabled: true, ...STORE.promo, ...AR.promo }, whatsapp: STORE.whatsapp, instapay: STORE.instapay,
  phone: STORE.phone, email: STORE.email, address: STORE.address, hours: STORE.hours, ...AR.store, mapsUrl: STORE.mapsUrl,
  socials: STORE.socials, delivery: Object.entries(STORE.delivery).map(([city, fee]) => ({ city, fee, ar: AR.delivery[city] || '' })),
  dashboardUrl: '',
  categories: CATEGORIES.map(c => ({ name: c.name, tag: c.tag, bg: c.bg, subs: c.subs, ar: (AR.categories[c.name] || {}).ar || '', subs_ar: (AR.categories[c.name] || {}).subs || {} })),
};
const ar = id => AR.products[id] || { name: '', desc: '', material: '', size: '', color: '', comes: [] };

let seed = `-- ALLURE Boutique — starting catalogue and store settings (English + Arabic).
-- Run once after schema.sql. Generated by tools/build_seed.js — edit products later in the dashboard.

insert into public.settings (id, data) values (1, ${j(settings)})
on conflict (id) do update set data = excluded.data;

insert into public.products (id, code, name, cat, sub, price, old_price, material, size, color, comes_with, description,
  flags, stock, rating, reviews_count, popularity, bg, options, created_at,
  name_ar, description_ar, material_ar, size_ar, color_ar, comes_with_ar) values
`;
seed += PRODUCTS.map(p => { const a = ar(p.id); return `  (${[q(p.id), q(p.code), q(p.name), q(p.cat), q(p.sub || null), p.price, p.oldPrice || 'null',
  q(p.material), q(p.size), q(p.color), arr(p.comesWith), q(p.desc), j(p.flags), p.inStock ? 10 : 0, p.rating, p.reviews,
  p.popularity, q(p.bg), j(p.options || {}), q(p.addedAt + 'T12:00:00Z'),
  q(a.name), q(a.desc), q(a.material), q(a.size), q(a.color), arr(a.comes)].join(', ')})`; }).join(',\n');
seed += `\non conflict (id) do nothing;

insert into public.promo_codes (code, percent) values ${Object.entries(STORE.promoCodes).map(([c, r]) => `(${q(c)}, ${Math.round(r * 100)})`).join(', ')}
on conflict (code) do nothing;

insert into public.reviews (user_id, name, rating, text, approved, created_at) values
${SEED_REVIEWS.map(r => `  (null, ${q(r.name)}, ${r.rating}, ${q(r.text)}, true, ${q(r.date + 'T12:00:00Z')})`).join(',\n')};
`;
fs.writeFileSync(path.join(root, 'supabase', 'seed.sql'), seed);

// ── arabic.sql: fills Arabic only where it's still empty, never overwrites the owner's edits ──
const catMap = Object.fromEntries(Object.entries(AR.categories).map(([k, v]) => [k, { ar: v.ar, subs: v.subs }]));
let upd = `-- ALLURE Boutique — add Arabic text to an existing store.
-- Run in Supabase → SQL Editor AFTER running the latest schema.sql. Safe to run more than once:
-- it only fills Arabic fields that are still empty and never changes anything you've edited.

update public.products p set
  name_ar        = case when p.name_ar = '' then v.name_ar else p.name_ar end,
  description_ar = case when p.description_ar = '' then v.description_ar else p.description_ar end,
  material_ar    = case when p.material_ar = '' then v.material_ar else p.material_ar end,
  size_ar        = case when p.size_ar = '' then v.size_ar else p.size_ar end,
  color_ar       = case when p.color_ar = '' then v.color_ar else p.color_ar end,
  comes_with_ar  = case when cardinality(p.comes_with_ar) = 0 then v.comes_with_ar else p.comes_with_ar end
from (values
${Object.entries(AR.products).map(([id, a]) => `  (${[q(id), q(a.name), q(a.desc), q(a.material), q(a.size), q(a.color), arr(a.comes)].join(', ')})`).join(',\n')}
) as v(id, name_ar, description_ar, material_ar, size_ar, color_ar, comes_with_ar)
where p.id = v.id;

update public.settings s set data = s.data
  || jsonb_build_object('promo', ${j(AR.promo)} || coalesce(s.data->'promo', '{}'::jsonb))
  || jsonb_build_object('address_ar', coalesce(nullif(s.data->>'address_ar', ''), ${q(AR.store.address_ar)}),
                        'hours_ar',   coalesce(nullif(s.data->>'hours_ar', ''), ${q(AR.store.hours_ar)}))
  || jsonb_build_object('categories', (
       select coalesce(jsonb_agg(c || jsonb_build_object(
                'ar', coalesce(nullif(c->>'ar', ''), m.v->>'ar', ''),
                'subs_ar', coalesce(m.v->'subs', '{}'::jsonb) || coalesce(c->'subs_ar', '{}'::jsonb)) order by ord), '[]'::jsonb)
       from jsonb_array_elements(coalesce(s.data->'categories', '[]'::jsonb)) with ordinality as e(c, ord)
       left join jsonb_each(${j(catMap)}) m(k, v) on m.k = c->>'name'))
  || jsonb_build_object('delivery', (
       select coalesce(jsonb_agg(d || jsonb_build_object('ar', coalesce(nullif(d->>'ar', ''), ${j(AR.delivery)}->>(d->>'city'), '')) order by ord), '[]'::jsonb)
       from jsonb_array_elements(coalesce(s.data->'delivery', '[]'::jsonb)) with ordinality as e(d, ord)))
where s.id = 1;
`;
fs.writeFileSync(path.join(root, 'supabase', 'arabic.sql'), upd);
console.log('wrote supabase/seed.sql and supabase/arabic.sql:', PRODUCTS.length, 'products');
